# Generated by Django 4.2.27 on 2026-02-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PosterAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=100, unique=True)),
                ('access_token', models.CharField(max_length=255)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('user_info', models.JSONField(blank=True, default=dict)),
                ('owner_info', models.JSONField(blank=True, default=dict)),
                ('tariff_info', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
