# Generated by Django 4.2.27 on 2026-02-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_dailyreport_reporttemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('issue_type', models.CharField(max_length=80)),
                ('severity', models.IntegerField(default=1)),
                ('message', models.TextField()),
                ('context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductsSalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=32, unique=True)),
                ('date_start', models.DateTimeField(blank=True, null=True)),
                ('date_close', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('sum', models.BigIntegerField(default=0)),
                ('payed_sum', models.BigIntegerField(default=0)),
                ('payed_cash', models.BigIntegerField(default=0)),
                ('payed_card', models.BigIntegerField(default=0)),
                ('payed_bonus', models.BigIntegerField(default=0)),
                ('payed_third_party', models.BigIntegerField(default=0)),
                ('payed_cert', models.BigIntegerField(default=0)),
                ('spot_id', models.CharField(blank=True, max_length=32)),
                ('table_id', models.CharField(blank=True, max_length=32)),
                ('user_id', models.CharField(blank=True, max_length=32)),
                ('client_id', models.CharField(blank=True, max_length=32)),
                ('service_mode', models.CharField(blank=True, max_length=16)),
                ('processing_status', models.CharField(blank=True, max_length=16)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
