# Generated by Django 4.2.27 on 2026-02-03 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0003_dataissue_paymentsreport_productssalesreport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPosterAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_base_url', models.CharField(max_length=255)),
                ('api_token', models.CharField(max_length=255)),
                ('auth_style', models.CharField(default='query_token', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='poster_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
