# Generated by Django 4.2.27 on 2026-02-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_insight_userposteraccount_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataissue',
            name='ignored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dataissue',
            name='ignored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
