# Generated by Django 4.2.27 on 2026-02-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_dataissue_ignored_dataissue_ignored_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_id', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=120)),
            ],
        ),
    ]
