# Generated by Django 4.2.27 on 2026-02-03 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0008_spotssalesreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_ids', models.CharField(default='', max_length=255)),
                ('auto_daily', models.BooleanField(default=True)),
                ('daily_time', models.CharField(default='23:59', max_length=5)),
                ('timezone', models.CharField(default='UTC', max_length=40)),
                ('metrics', models.JSONField(blank=True, default=list)),
                ('include_spots', models.BooleanField(default=True)),
                ('include_issues', models.BooleanField(default=True)),
                ('include_returns', models.BooleanField(default=True)),
                ('template_name', models.CharField(blank=True, default='', max_length=120)),
                ('notify_issue_types', models.JSONField(blank=True, default=list)),
                ('last_sent_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
