# Generated by Django 4.2.27 on 2026-02-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_telegramsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramsettings',
            name='auto_per_spot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegramsettings',
            name='auto_shift_close',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegramsettings',
            name='shift_template_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='telegramsettings',
            name='spot_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
