"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-&ypt4$**ha0p=v_*7$)oe4)$)os*_j!4^u6_kvuu*x4zfqgror",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "1") == "1"

_allowed_hosts = os.getenv("DJANGO_ALLOWED_HOSTS", "")
ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts.split(",") if h.strip()]
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",")
    if origin.strip()
]


# Application definition

INSTALLED_APPS = [
    'reports',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

# Auth
LOGIN_REDIRECT_URL = "/reports/"
LOGOUT_REDIRECT_URL = "/accounts/login/"
# Poster API settings
POSTER_API_BASE_URL = os.getenv("POSTER_API_BASE_URL")
POSTER_API_TOKEN = os.getenv("POSTER_API_TOKEN")
POSTER_AUTH_STYLE = os.getenv("POSTER_AUTH_STYLE")

# Poster OAuth app credentials
POSTER_APP_ID = os.getenv("POSTER_APP_ID")
POSTER_APP_SECRET = os.getenv("POSTER_APP_SECRET")

# Client screen (public display) settings
CLIENT_SCREEN_POSTER_BASE_URL = os.getenv("CLIENT_SCREEN_POSTER_BASE_URL")
CLIENT_SCREEN_POSTER_TOKEN = os.getenv("CLIENT_SCREEN_POSTER_TOKEN")
CLIENT_SCREEN_POSTER_AUTH_STYLE = os.getenv("CLIENT_SCREEN_POSTER_AUTH_STYLE")
CLIENT_SCREEN_ORDER_ENDPOINT = os.getenv("CLIENT_SCREEN_ORDER_ENDPOINT")
CLIENT_SCREEN_ORDER_ID_PARAM = os.getenv("CLIENT_SCREEN_ORDER_ID_PARAM")
CLIENT_SCREEN_ORDER_NUMBER_PATH = os.getenv("CLIENT_SCREEN_ORDER_NUMBER_PATH")
CLIENT_SCREEN_ITEMS_PATH = os.getenv("CLIENT_SCREEN_ITEMS_PATH")
CLIENT_SCREEN_ITEM_NAME_PATH = os.getenv("CLIENT_SCREEN_ITEM_NAME_PATH")
CLIENT_SCREEN_ITEM_QTY_PATH = os.getenv("CLIENT_SCREEN_ITEM_QTY_PATH")
CLIENT_SCREEN_ITEM_PRICE_PATH = os.getenv("CLIENT_SCREEN_ITEM_PRICE_PATH")
CLIENT_SCREEN_ITEM_TOTAL_PATH = os.getenv("CLIENT_SCREEN_ITEM_TOTAL_PATH")
CLIENT_SCREEN_TOTAL_PATH = os.getenv("CLIENT_SCREEN_TOTAL_PATH")
CLIENT_SCREEN_CURRENCY_SYMBOL = os.getenv("CLIENT_SCREEN_CURRENCY_SYMBOL", "€")
CLIENT_SCREEN_AMOUNT_SCALE = float(os.getenv("CLIENT_SCREEN_AMOUNT_SCALE", "100"))
CLIENT_SCREEN_POLL_SECONDS = int(os.getenv("CLIENT_SCREEN_POLL_SECONDS", "5"))
CLIENT_SCREEN_DEMO_MODE = os.getenv("CLIENT_SCREEN_DEMO_MODE", "1") == "1"
CLIENT_SCREEN_ORDER_PARAMS_JSON = os.getenv("CLIENT_SCREEN_ORDER_PARAMS_JSON", "")
CLIENT_SCREEN_WEBHOOK_SECRET = os.getenv("CLIENT_SCREEN_WEBHOOK_SECRET", "")
CLIENT_SCREEN_WEBHOOK_REFRESH_ENDPOINT = os.getenv("CLIENT_SCREEN_WEBHOOK_REFRESH_ENDPOINT", "")
CLIENT_SCREEN_WEBHOOK_ID_PARAM = os.getenv("CLIENT_SCREEN_WEBHOOK_ID_PARAM", "")

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
